### ISSUE TITLE
キタエル × groovyのテストコード

### ISSUE THREAD

**Issue by GitEngHar** [GitEngHar/learnJava#35]
参考ブログ  
https://qiita.com/hondaYoshitaka/items/0f21368938ea9828b709
https://tech.asoview.co.jp/entry/2019/12/23/101942

**Comment by GitEngHar** [comment]
##  触ってみる

### 🔍groovy って そもそも何

開発速度が爆速になる `Rails` が普及する中 おいてけぼりな `Java`  
`Java` で `Rails` チックに動かせる `Java` に寄り添った言語として `Groovy ? Grails` ができたんだとか  
`Ruby` の機能や概念を取り入れ `Java` と同じような書き方をできる  


### 👨‍💻groovy で テストコードを書く



### ❓groovyの何が良いのか? JUNITではなく

https://speakerdeck.com/disc99/javafalsetesutogroovydeiifalsedehanaikatoiuhua?slide=49
極論、JavaテストをJunitで書くと、複雑化・肥大化するけど groovy なら そのあたりが解消するからという結論そう

**Comment by GitEngHar** [comment]
## 環境構築を終わるまで

### 🏝️PlayGroundで遊ぶ

- PlayGround環境
https://groovyide.com/playground

- 参考にしたブログ
https://zenn.dev/yonekubo/books/6f4bde620a7bac/viewer/8367af


#### 試す

明示的に getter を指定してみた  

<details>

```groovy
class Personal {
    private int age;
    private String name;
    Personal(int age, String name){
        this.age = age;
        this.name = name;
    }
    int getAge(){
        return this.age; 
    }
    String getName(){
        return this.name;
    }
}

def returnHello(int age,String name){
    Personal personal = new Personal(age,name)
    println("Age: " + personal.getAge() + " , Name: " + personal.getName())
}

returnHello(10,"haru")
```

</details>

暗黙的なgetterを利用した  

<details>

```groovy
class Personal {
    private int age;
    private String name;
    Personal(int age, String name){
        this.age = age;
        this.name = name;
    }
}

def returnHello(int age,String name){
    Personal personal = new Personal(age,name)
    println("Age: " + personal.age + " , Name: " + personal.name)
}

returnHello(10,"haru")
```

</details>


assertの挙動

<details>

```groovy
def confirmAssert(){
    int value1 = 1
    int value2 = 2
    assert value1 == value2 // 等値を記述する
}
```

結果
```text
***
Error at line: 18
***
Assertion failed: 

assert value1 == value2 // 等値を記述する
       |      |  |
       1      |  2
              false

	at groovyide_com.confirmAssert(groovyide_com:18)
	at groovyide_com$confirmAssert$0.callCurrent(Unknown Source)
	at groovyide_com.run(groovyide_com:22)
	at com.groovyide.ExecutorService$2.run(ExecutorService.java:253)
```

</details>

クロージャの挙動を確認する

<details>

```groovy

//closureの挙動を確認
def confirmClosure(){
    def d = {x -> x*2}
    def counter = {d(2)*2}
    def plusCounter = {
        // ; で改行なしで記述できる
        def t = 2; t=d(t)*2; t=t+1;
    }
    println("closure in:2 , out:" + d(2))
    println("closure count:2, count:" + counter())
    println("closure plusCount:2, plusCount:" + plusCounter())
}

confirmClosure()


```

</details>

テストコードを書いてみる

<details>

```groovy
class Personal {
    private int age;
    private String name;
    Personal(){
    }
    Personal(String name){
        this.name = name;
    }
    Personal(int age, String name){
        this.age = age;
        this.name = name;
    }
}

def "Personalで格納と取得できること" (){
    // 満たすべき前提条件を記述
    given: "Personalオブジェクトと格納対象の文字列がある"
    def str = "haru"
    and: "テスト対象のオブジェクト"
    def sut = new Personal(str) //SystemUnderTestでテスト対象を表すsut
    
    // 検証したい振る舞いを記述する
    when: "strの値をオブジェクトから取得する"
    def result = sut.name
    
    then: "strで宣言した値をオブジェクトから取得できている"
    result == "haru"
}

```

</details>

PlayGroundでテストケースの実行はできず..
しかし仕組みが分かってよかった

**Comment by GitEngHar** [comment]
## Groovy で UnitTest , IntegrationTestを学ぶ

文字が１つ違うとアプリケーションは壊れるしテストって大事だよねと

### Unitテスト

#### Unitテストについて

- クラスや関数の挙動をテストする
  - 振る舞いのキャッシュへの依存など? プログラムの Side effect(副作用) が関係しないテスト
- クラスや関数のスコープによっては呼び出せずテストできないことがあるのでそのあたりはアノテーションを使おう
- 依存が存在する部分はMockにしよう
- OSやファイルシステムへは依存しないはず

Mockは内部の処理を無視して 出力結果だけを定義する   

#### コード

https://github.com/GitEngHar/WorkUp/pull/36

### 参考
#### 📚 知識
https://circleci.com/blog/unit-testing-vs-integration-testing/

#### 💻 技術
https://www.youtube.com/watch?v=lU-eha2bnL0
