### ISSUE TITLE
Object指向

### ISSUE THREAD

**Issue by GitEngHar** [GitEngHar/learnJava#5]
https://github.com/GitEngHar/learnJava/issues/1
上記に紐づく issue 

https://github.com/GitEngHar/learnJava/tree/main/JavaNative/Books/honkaku/Object/src
検証ソースコード

**Comment by GitEngHar** [comment]
````text

## テンプレ用
### 例1 現在時刻の取得

#### コード

```java
```

#### 実行結果

```text
```

**Comment by GitEngHar** [comment]
### 参照型(ミュータブル)とプリミティブ型(イミュータブル)

- 参照型は参照元の値が変化する
- プリミティブ型は参照元の値が変化しない

[それぞれのメリット / デメリットについて](https://github.com/GitEngHar/learnJava/issues/5#issuecomment-2057976068)

### 可視性

#### グッドプラクティス

狭い範囲で可視性を設定するのが良いとされている  
全てを `public` とすると責任範囲が曖昧になり、本来書き換えられたくないスコープからの変更を受けることとなるため  

#### 可視性 と 修飾子

- 全てのクラスから利用可能 
  - public
  - public
- サブクラス 同一パッケージ内
  - protected
  - protected
- 同一パッケージのクラスのみ
  - packeage private
  - 指定なし
- 自身のクラスのみ
  - private
  - private    

#### 修飾子のユースケース

- private
  - クラス内部でのみ利用するフィールド変数 
- public
  - 外部からアクセスするメソッド
- protected
  - 継承して書き換えたいメソッド
    - メソッドがprivateだと継承は可視性の範囲外になるので、エラーになりオーバライドできない 

### オブジェクトライフサイクル

オブジェクトライフサイクルはオブジェクト生成から破棄されるまでの時間

#### ライフサイクルの種類

- ローカル変数
- インスタンス変数
- クラス変数

```java
public Class Test{
 static public int aaa; // クラス変数
 public int bbb; // インスタンス変数
 void test(){
   int a = 1; //ローカル変数
   if(this.aaa > 0){
     int b = 1; // ローカル変数
   }
 }
}

```

### オブジェクトのライフサイクル

### インターフェースと抽象クラス

良いAPI・設計をするにはポリモーフィズム(多様性)を理解するべし  
異なるクラス(java.util.ArrayList , java.util.LinkedList)で同じような機能のメソッドがあった場合、メソッド名が異なるとプログラマからの利便性が落ちる  
2つのクラスで値を保持する型を同様のインターフェースにしていれば、利用が楽になる  
クラスが異なった場合でも値を保持するインターフェースが同一であるため、プログラマはその差分を意識することなく利用してもいい  
[Link](https://github.com/GitEngHar/learnJava/issues/5#issuecomment-2061233524)

#### インターフェースと抽象クラスの違い

インターフェース は 定数のみ宣言することができる 。**「定義」** としてとらえられる。
抽象クラス は abstracutを利用でき、インスタンス化することはできないが他は通常通り。 **「ひな形」「共通処理」** で利用される。

- インターフェースの詳細
  -   インターフェースはコードの特性といえる。インターフェースで同様の特性を持ったクラスを作成できる
  - インターフェースで定義されてあるメソッド以外は外部からの呼び出しに制限がかかる
  - 定数インターフェースと呼ばれる定数のみ定義したものがあり、複数のクラスで定数を共有できる(非推奨)
    - 定数は専用クラスに定義しておき、 classname.variable 指定しよう
    - static import を利用することで簡単に定数を利用できる 

- 抽象クラスの詳細
  - 複数クラスでスーパークラスを切り出し、抽象化・共通化したもの
  - 実装者からすればひな形で、最小限の実装はされてあるので、付け加えるのみ 

抽象クラスを利用すると、共通処理となるため継承元のクラスとの依存関係が強まる  
依存関係を弱め特性を一致させたい場合に インターフェースを利用する

インターフェース に定義できるのは `public` のみ  
返り値がオブジェクトであるメソッドをファクトリークラスと呼ぶ
ファクトリークラスを用いることで、Interfaceをimportするのみで実装クラスを扱うことができる

**Comment by GitEngHar** [comment]
## プリミティブ型と参照型の値渡し

### プリミティブ型 参照元の値は変化しない

#### コード

```java
    public void ex1(){
        int value = 2;
        calcEx1(value);
        System.out.println("value1 : " + value);
    }

    public void calcEx1(int value){
        value ++;
        System.out.println("value2 : " + value);
    }
```

#### 実行結果

```text
value2 : 3
value1 : 2
```

### 参照型の値渡し 

#### コード

```java
public void ex2(){
        Entity et = new Entity();
        et.value = 1;
        calcEx2(et);
        System.out.println("value ex2-1:" + et.value);
    }

    public void calcEx2(Entity et){
        et.value ++;
        System.out.println("value ex2-2:" + et.value);
    }

class Entity{
    int value;
}
```

#### 実行結果

```text
value ex2-2:2
value ex2-1:2
```

引数でオブジェクトを受け取り、値を書き換えた場合、参照元オブジェクトと同様のものであれば値は共有される  
※ 実装する際はこの点に注意が必要  
基本、帰り値が `void` の場合はオブジェクトを新しくすることは考えずらいという思想もある

**Comment by GitEngHar** [comment]
## イミュータブルな値

### Stringクラスで見るイミュータブルな値

#### コード

```java
public void ex3(){
        String st = "This is a pen";
        String st2 = st.replace("pen","ball");
        System.out.println("string1: " + st);
        System.out.println("string2: " + st2);
    }
```

#### 実行結果

```text
string1: This is a pen
string2: This is a ball
```

‘st‘ 値を `replace` 後内容を確認したが値は書き換わっていない  
変換した値を利用する際は別の変数に代入している

**Comment by GitEngHar** [comment]
### Tips

`a += "aaa"` や `a++;` 等は既存のオブジェクトの値が書き換わっているように見えるが事実、別のオブジェクトを生成し元のオブジェクトを置き換えている  
そのため、元のオブジェクトの値が書き換わっているわけではない

**Comment by GitEngHar** [comment]
## ミュータブルなクラス

### StrinBuffer(append) , StringBuilder(incrementAndGet)

操作で値が変わるクラスと実行メソッド

#### コード

```java
public void ex4(){
        StringBuffer sb = new StringBuffer("Hello");
        System.out.println("実行前 : " + sb);
        sb.append(" World");
        System.out.println("実行後 : " + sb);
        AtomicInteger ati = new AtomicInteger(1);
        System.out.println("実行前 : " + ati );
        ati.incrementAndGet();
        System.out.println("実行後 : " + ati);
    }
```

#### 実行結果

```text
実行前 : Hello
実行後 : Hello World
実行前 : 1
実行後 : 2
```

オブジェクト自体の値を書き換えることができる場合、ミュータブルな値といえる

**Comment by GitEngHar** [comment]
### ミュータブル イミュータブルまとめ

- イミュータブル
  - 元の値が書き換わらないため、意図しない挙動にならない。そのため、扱いやすい**メリット**がある
  -  新たに毎回オブジェクトを生成するので、処理に時間がかかる**デメリット**がある
- ミュータブル
  - 元の値が変わるので意図しない挙動に配慮が必要な**デメリット**がある
  - 1つのオブジェクトを使いまわせるので処理が速い**メリット**がある

**Comment by GitEngHar** [comment]
## 可視性
### 例1 現在時刻の取得

#### ディレクトリ構成

![image](https://github.com/GitEngHar/learnJava/assets/119464648/7812c752-bd75-4d5a-9977-85a2eb26dc92)


#### コード

App.java

```java
package apps;

public class App{
    public static void main(String[] args) throws Exception {
        ObjectExec obe = new ObjectExec();    
        obe.exec();
    }
}

```


ObjectExec.java

```java
package apps;
import objects.ObjectTest;

public class ObjectExec extends ObjectTest{
    public void exec(){
        super.ex5(1); // 継承しているためコンパイルが通る
        super.ex6(); // 同一パッケージではないことによるエラー
        super.ex7(); // 同一クラスではないことによるエラー
    }
}

```

ObjectTest.java

```java
    protected void ex5(int a){
        a += 1;
        System.out.println(a);
    }
    void ex6(int a){
        a += 1;
        System.out.println(a);
    }
    private void ex7(int a){
        a += 1;
        System.out.println(a);
    }
```

#### 実行結果

```text
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The method ex6(int) in the type ObjectTest is not applicable for the arguments ()

        at apps.ObjectExec.exec(ObjectExec.java:7)
        at apps.App.main(App.java:6)
```

**Comment by GitEngHar** [comment]
### Tips

外部から可視性のスコープ外メソッドにアクセスすることもできる  
`リフレクション` という機能を用いる  
可視性を無視する機能なので、コードの運用性が低下する

**Comment by GitEngHar** [comment]
## 多様性
### 異なるクラスで同様の型を持つ

#### コード

```java
    protected void ex8(){
        List<Integer> list = new ArrayList(); 
        List<Integer> linkedList = new LinkedList();
        list.add(1);
        list.add(2);
        linkedList.add(2);
        linkedList.add(3);
    }
```

**Comment by GitEngHar** [comment]
## 多様性?
### static値の取得

#### コード

```java
package apps;

public class UserInfo {
        static String username = "Haru";
        static int old = 24;
        static int number = 22;
}
```

```java
import static apps.UserInfo.*;
public class ObjectExec extends ObjectTest{
    public void exec(){
        //super.ex5(1); // 継承しているためコンパイルが通る
        //super.ex6(); // 同一パッケージではないことによるエラー
        //super.ex7(); // 同一クラスではないことによるエラー
        System.out.println(username);
        System.out.println(old);
        System.out.println(number);
    }
}
```


#### 実行結果

```text
Haru
24
22
```

**Comment by GitEngHar** [comment]
## Interfaceの利用
### ファクトリークラスを含めたInterface

ファクトリークラスはオブジェクトを返すメソッド  
Interfaceに定義しておけるものは `public` のみ(外部から利用してほしいメソッドのみをInterfaceに記述する)  

#### コード

◆ Interface 

```java
package apps;

public interface DefaultFunction {
    String hello();
    public static DefaultFunction newinstance(){
        return new Function(); //ファクトリークラス
    } 
}
```

◆ interfaceを利用する実装クラス

```java
package apps;

public class Function implements DefaultFunction {
    String sayWord = "hello";
    
    public String hello(){
        return this.sayWord;
    }

    public void setWord(String word){
        this.sayWord = word;
    }
}
```

◆ 実装クラスを利用する クラス

```java
import apps.DefaultFunction;
import apps.Function;

    protected void ex9(){
        DefaultFunction fu = new Function();
        //DefaultFunction fu = DefaultFunction.newinstance();
        System.out.println(fu.hello());
    }
```

#### 実行結果

```text
hello
```

### ファクトリークラスの活用 実装クラスを import せずに利用する

#### コード

◆ 実装クラスを利用する クラス

```java
import apps.DefaultFunction;
//import apps.Function; 不要なのでコメントアウト

    protected void ex9(){
        //DefaultFunction fu = new Function(); 不要なのでコメントアウト
        DefaultFunction fu = DefaultFunction.newinstance();
        System.out.println(fu.hello());
    }
```
